stages:
  - name: Compilando Código
    steps:
      - runScriptConfig:
          image: maven:3.6.3-jdk-11-slim
          shellScript: |-
            mvn clean install package
  - name: Publicando Imagem
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: dsantana87/builders-service:builders-service:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: dsantana87/builders-service:builders-service
#  - name: Deploy
#    steps:
#      - applyYamlConfig:
#          path: ./deployment.yml
#  - name: Construindo Image
#    steps:
#      - runScriptConfig:
#          image: dsantana87/builders-service:builders-service
#          shellScript: |-
#            mkdir -p /go/src/github.com/rancher
#            ln -s `pwd` /go/src/github.com/rancher/pipeline-example-go
#            cd /go/src/github.com/rancher/pipeline-example-go
#            go build -o bin/hello-server
#            go test -cover
#  - name: Publish
#    steps:
#      - publishImageConfig:
#          dockerfilePath: ./Dockerfile
#          buildContext: .
#          tag: go-server:${CICD_EXECUTION_SEQUENCE}
#  - name: Deploy
#    steps:
#      - applyYamlConfig:
#          path: ./deployment.yml