stages:
  - name: Compilando Código
    steps:
      - runScriptConfig:
          image: openjdk:11
          shellScript: |-
            mvn -U clean install package
#  - name: Build
#    steps:
#      - runScriptConfig:
#          image: dsantana87/builders-service:builders-service
#          shellScript: |-
#            mkdir -p /go/src/github.com/rancher
#            ln -s `pwd` /go/src/github.com/rancher/pipeline-example-go
#            cd /go/src/github.com/rancher/pipeline-example-go
#            go build -o bin/hello-server
#            go test -cover
#  - name: Publish
#    steps:
#      - publishImageConfig:
#          dockerfilePath: ./Dockerfile
#          buildContext: .
#          tag: go-server:${CICD_EXECUTION_SEQUENCE}
#  - name: Deploy
#    steps:
#      - applyYamlConfig:
#          path: ./deployment.yml