apiVersion: apps/v1
kind: Deployment
metadata:
  name: builders-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: builders-service
  template:
    metadata:
      labels:
        app: builders-service
    spec:
      containers:
        - name: builders-service
          image: dsantana87/builders-service:builders-service
          env:
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=default,prod  -Duser.timezone=America/Sao_Paulo -Doracle.jdbc.fanEnabled=false"
            - name: SPRING_DATASOURCE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: builders-service-configmap
                  key: SPRING_DATASOURCE_PLATFORM
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              valueFrom:
                configMapKeyRef:
                  name: builders-service-configmap
                  key: SPRING_DATASOURCE_DRIVER-CLASS-NAME
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: builders-service-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: builders-service-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: builders-service-secret
                  key: SPRING_DATASOURCE_PASSWORD
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8087
#          envFrom:
#          - configMapRef:
#              name: builders-service-configmap
#          - secretRef:
#              name: builders-service-secret
