---
apiVersion: v1
kind: Service
metadata:
  name: builders-service
spec:
  type: NodePort
  selector:
    app: builders-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #namespace: go
  name: builders-service-ingress

spec:
  rules:
    - host: builders.service.rancher.devopsninja.com.br
      http:
        paths:
          - path: /
            backend:
              serviceName: builders-service
              servicePort: 80
