CREATE TABLE `cliente` (
  `PK_CLIENTE` bigint NOT NULL AUTO_INCREMENT,
  `DS_NOME` varchar(100) DEFAULT NULL,
  `DS_EMAIL` varchar(100) DEFAULT NULL,
  `NUMERO_REGISTRO` varchar(20) DEFAULT NULL,
  `DT_NASCIMENTO` date DEFAULT NULL,
  PRIMARY KEY (`PK_CLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `telefone` (
  `PK_TELEFONE` bigint NOT NULL AUTO_INCREMENT,
  `DS_NUMERO` varchar(12) DEFAULT NULL,
  `FK_CLIENTE` bigint DEFAULT NULL,
  PRIMARY KEY (`PK_TELEFONE`),
  KEY `FK_TELEFONE_1_idx` (`FK_CLIENTE`),
  CONSTRAINT `FK_TELEFONE_1` FOREIGN KEY (`FK_CLIENTE`) REFERENCES `cliente` (`PK_CLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
